global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertas.devops.ec2@gmail.com'
  smtp_auth_username: 'alertas.devops.ec2@gmail.com'
  smtp_auth_password: 'vhgg fmwr absm fuuu'
  smtp_require_tls: true
route:
  receiver: 'correo-devops'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
receivers:
- name: 'correo-devops'
  email_configs:
  - to: 'noe_-_01@hotmail.com'
    send_resolved: true
